name: scbm
channels:
  - pytorch
  - nvidia
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.12
  - pytorch-cuda
  - pytorch
  - torchvision
  - wandb
  - scikit-learn
  - tqdm
  - torchmetrics
  - matplotlib
  - conda-forge::hydra-core
  - plotly
  - anaconda::seaborn
  - transformers
  - pip
  - pip:
    - pytorch-minimize

